[workspace]
members = ["pusu-client", "pusu-client-lib", "pusu-protocol", "pusu-server", "pusu-server-lib"]
resolver = "3"

[workspace.dependencies]
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
thiserror = "2.0.12"

[profile.release]
debug = true
